### ISSUE TITLE
Which version of numpy is compatible with this repo?

### ISSUE THREAD

**Issue by litingfeng** [HaohanWang/PAR_experiments#3]
Hi Haohan,

I've tried to use your code to train on Cifar10 by running `python cnn_PAR.py`, but met some problems:

I installed tensorflow1.10.0, but got an error `ImportError: numpy.core._multiarray_umath failed to import`. Referring [this](https://github.com/numpy/numpy/issues/11871#issuecomment-462076933) site, I upgrade numpy to 1.17, which is not compatible with the tensorflow and I stuck here 

`/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/freespace/local/tl601/anaconda3/envs/PAR_Cifar/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a
future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Namespace(adv_flag=1, adv_learning_rate=0.001, augmentation=1, batch_size=128, epochs=400, gpu_id='1', input='/common/users/tl601/PAR', input_epoch=399, lam=1.0, learning_rate=0.1, output='/common/users/tl601/PAR', start_epoch=250)
WARNING:tensorflow:From /ilab/users/tl601/Research/PAR/PAR_experiments/Cifar10/util/nn_util.py:70: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a
future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From cnn_PAR.py:75: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Starting training`

Could you give me some hints to solve this problem?

I'll really appreciate it if you reply.

Thanks,

**Comment by litingfeng** [comment]
The training is running on cpu, while I checked with `nvidia-smi` and thought it was stuck.

**Comment by SongweiGe** [comment]
Thanks for your interest! I've updated the requirement file. Please let me know if the problems are still not solved.
